version: 2
jobs:
  build:
    docker:
      - image: node:lts
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: node:lts
    steps:
      - run: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
        requires:
          - build